# Generated by Django 3.2.9 on 2021-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phno', models.CharField(default='', max_length=100)),
                ('passwd', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
