# Generated by Django 3.2.9 on 2021-11-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='image')),
                ('cloth', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
