# Generated by Django 3.2.9 on 2021-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_dress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
