# Generated by Django 3.2.9 on 2021-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_dress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
