# Generated by Django 3.2.9 on 2021-11-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_dress_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressname', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('drsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.dress')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.reg_tb')),
            ],
        ),
    ]
