# Generated by Django 3.2.9 on 2021-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_cart_reg_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_reg_tb',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
