# Generated by Django 3.2.9 on 2021-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_order_reg_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_reg_tb',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
