# Generated by Django 3.2.9 on 2021-11-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_order_reg_tb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_reg_tb',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
