# Generated by Django 3.2.9 on 2021-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_cart_reg_tb_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_reg_tb',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
